# Generated by Django 4.2.1 on 2023-10-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_alter_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='date_of_payment',
        ),
    ]
